#!/bin/bash

# Change policy to DROP for INPUT and FORWARD
iptables -P INPUT DROP 
iptables -P FORWARD DROP 

# Allow established and related connection & tcp on port 40
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT 
iptables -A INPUT -p tcp --dport 40 -j ACCEPT 

# Drop all invalid packets
iptables -A INPUT -m state --state INVALID -j DROP
iptables -A FORWARD -m state --state INVALID -j DROP
iptables -A OUTPUT -m state --state INVALID -j DROP

# Stop DOS icmp flooding
iptables -A INPUT -p icmp -m limit --limit 2/second --limit-burst 2 -j ACCEPT

# Stop DOS SYN flooding
iptables -A INPUT -p tcp -m state --state NEW -m limit --limit 2/second --limit-burst 2 -j ACCEPT
# other option : iptables -A INPUT -p tcp --dport 80 -m limit --limit 25/minute --limit-burst 100 -j ACCEPT

# Attempt to block portscans
# Anyone who tried to portscan us is locked out for an entire day.
iptables -A INPUT   -m recent --name portscan --rcheck --seconds 86400 -j DROP
iptables -A FORWARD -m recent --name portscan --rcheck --seconds 86400 -j DROP
